app_name: ENIL
tag_prefix: v

version:
  source: source/macOS/Info.plist
  keys:
    - CFBundleShortVersionString
    - CFBundleVersion
  plists:
    - source/macOS/Info.plist
    - source/iOS/Info.plist

release:
  commit_message: "Version {version}"

targets:
  - name: macOS
    workdir: .
    build:
      - make macOS-clean
      - make macOS-release
    artifact: build/macOS/release/ENIL.zip
    asset_name: ENIL-{version}-macOS.zip

  - name: iOS
    workdir: .
    build:
      - make iOS-clean
      - make iOS-release
    artifact: build/iOS/release/ENIL.ipa
    asset_name: ENIL-{version}-iOS.ipa
