#import <AppKit/AppKit.h>
#import "AIWebViewController.h"
#import "ENILAccount.h"

@class StickerViewController;

@protocol StickerViewControllerDelegate <NSObject>
- (void)stickerViewController:(StickerViewController *)vc
               didSelectPackageId:(NSString *)packageId
                        stickerId:(NSString *)stickerId
                         isSticon:(BOOL)isSticon;
@end

/* Picker content mode. Opens in …None — a deliberate "never loaded" state so
 * the WebView renders nothing until the user explicitly picks Stickers or
 * Emoji. Without it the default tab pre-renders into the (still collapsed)
 * inspector at window-load and then flashes through the instant the pane is
 * first revealed in the other mode. */
typedef enum {
  StickerPickerModeNone = 0,
  StickerPickerModeSticker,
  StickerPickerModeSticon
} StickerPickerMode;

/* Inspector-pane sticker / sticon picker. The picker HTML is generated by
 * ENILAccount and resolves per-account media paths relative to the
 * baseURL we hand to AIWebViewController. Selection comes back via the
 * +handledURLSchemes (enil-sticker, enil-sticon) → -handleActionURL: hook
 * the base class wires to its WKWebView's navigation delegate.
 *
 * Tier: works on all three tiers via AIWebViewController, which uses
 * WKWebView on Middle/Modern and the legacy WebKit1 WebView on Legacy.
 * The picker HTML, +handledURLSchemes intercept, and incremental-JS
 * contract are identical across tiers because the base class hides the
 * WebView class behind a uniform surface. */
@interface StickerViewController : AIWebViewController {
 @private
  ENILAccount                          *engine_;
  id<StickerViewControllerDelegate> delegate_;
  StickerPickerMode                     mode_;
  BOOL                                  dirty_;
}

- (id)initWithEngine:(ENILAccount *)engine;
- (void)setDelegate:(id<StickerViewControllerDelegate>)delegate;
- (void)reloadData;
- (void)reloadActiveTabIfDirty;

/* Picker mode is driven from the host window's toolbar (a 3-segment control
 * that combines inspector visibility + picker mode). The setter is a no-op
 * when the requested mode already matches; otherwise it flips the mode (out
 * of the never-loaded …None state on first use) and reloads the active tab. */
- (BOOL)isSticonMode;
- (void)setSticonMode:(BOOL)sticon;

/* NO until the user has picked Stickers or Emoji at least once. The host
 * window consults this so a reveal that bypasses Show Stickers / Emoji can
 * fall back to a default tab rather than showing a blank pane. */
- (BOOL)hasSelectedMode;

@end
